### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'

### ISSUE THREAD

**Issue by zarembat** [snjypl/airflow-provider-grafana-loki#7]
Hi again,

I get the following error when retrieving logs in the UI:
```
apache-airflow-airflow-webserver-1   | [2022-12-21 08:02:36,557] {app.py:1456} ERROR - Exception on /get_logs_with_metadata [GET]
apache-airflow-airflow-webserver-1   | Traceback (most recent call last):
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 2077, in wsgi_app
apache-airflow-airflow-webserver-1   |     response = self.full_dispatch_request()
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1525, in full_dispatch_request
apache-airflow-airflow-webserver-1   |     rv = self.handle_user_exception(e)
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1523, in full_dispatch_request
apache-airflow-airflow-webserver-1   |     rv = self.dispatch_request()
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/flask/app.py", line 1509, in dispatch_request
apache-airflow-airflow-webserver-1   |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/auth.py", line 46, in decorated
apache-airflow-airflow-webserver-1   |     return func(*args, **kwargs)
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/decorators.py", line 80, in wrapper
apache-airflow-airflow-webserver-1   |     return f(*args, **kwargs)
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 71, in wrapper
apache-airflow-airflow-webserver-1   |     return func(*args, session=session, **kwargs)
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/www/views.py", line 1577, in get_logs_with_metadata
apache-airflow-airflow-webserver-1   |     logs, metadata = task_log_reader.read_log_chunks(ti, try_number, metadata)
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/log/log_reader.py", line 57, in read_log_chunks
apache-airflow-airflow-webserver-1   |     logs, metadatas = self.log_handler.read(ti, try_number, metadata=metadata)
apache-airflow-airflow-webserver-1   |   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/log/file_task_handler.py", line 267, in read
apache-airflow-airflow-webserver-1   |     log, metadata = self._read(task_instance, try_number_element, metadata)
apache-airflow-airflow-webserver-1   |   File "/opt/airflow/plugins/grafana_loki_provider/log/loki_task_handler.py", line 119, in _read
apache-airflow-airflow-webserver-1   |     end = ti.end_date + timedelta(hours=1)
apache-airflow-airflow-webserver-1   | **TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'**
```

This is a running task so indeed end_date is not set yet. I guess in such a case we need to use the current date.

**Comment by snjypl** [comment]
@zarembat  thanks for reporting this. sorry for the late response. the issue should be fixed in the latest version.   ref: https://github.com/snjypl/airflow-provider-grafana-loki/commit/8e6ea5fe1c281b8583875816988a095419eed204
